on:
  workflow_dispatch: {}
  schedule:
    # run every sunday at 03:23 AM
    - cron: "23 3 * * 0"

jobs:
  nix-flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/determinate-nix-action@v3

      - name: Update Nix flake inputs
        id: update
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.GH_TOKEN_FOR_FLAKE_UPDATES }} # Fine-grained token with contents and pull-requests write permissions
          branch: build/flake-update # Branch to create the PR from
          pr-title: "Update Nix flake inputs" # Title of PR to be created
          pr-labels: | # Labels to be set on the PR
            dependencies
            automated
          # Custom PR body. Removed note about running actions on the PR.
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```

      - name: Print PR info
        run: |
          echo "Pull request number is ${{ steps.update.outputs.pull-request-number }}."
          echo "Pull request URL is ${{ steps.update.outputs.pull-request-url }}."
